sudo: false
language: python
python:
  - 3.5
install:
    - pip install -r requirements.txt
before_script:
 - psql -c "CREATE DATABASE stackoverflowlite;" -U postgres
 - psql -c "CREATE USER postgres WITH PASSWORD 'passwprd';" -U postgres
script:
  - nosetests --with-coverage --cover-package=stackoverflowlite
  - coveralls
after_sucess:
  - coveralls
